services:
  gdb-client:
    image: axemsolutions/make_gnu-arm:13.2
    container_name: make_gnu-arm_container
    networks:
      - gdb-net
    volumes:
      - "..:/work"
    command: /bin/sh -c "while sleep 100; do :; done"

  gdb-server:
    image: axemsolutions/stlink-org:1.8.0
    container_name: stlink-org_container
    networks:
      - gdb-net
    volumes:
      - "..:/work"
    privileged: true
    command: /bin/sh -c "st-util"

networks:
  gdb-net:
    driver: bridge