services:
  gdb:
    image: axemsolutions/make_gnu_arm
    container_name: make_gnu_arm_container
    networks:
      - debug-net
    volumes:
      - "..:/work"
    command: /bin/sh -c "hostname -i; while sleep 100; do :; done"

  st-util:
    image: axemsolutions/stlink_org
    container_name: stlink_org_container
    networks:
      - debug-net
    volumes:
      - "..:/work"
    privileged: true
    command: /bin/sh -c "hostname -i; st-util"

networks:
  debug-net:
    driver: bridge